### PR TITLE
Gameloop

### LINKED ISSUE #50: Crash when stubgen includes `gameloop`
**Describe the bug**
Turns out that even though the `gameloop` in Codingame stubs is intended for interactive puzzles, some clashes such as this [Hanoi Tower](https://www.codingame.com/contribute/view/5119910629a6bc760199c643306ecabb14c31) one use it.

**To Reproduce**
```
clash fetch 5119910629a6bc760199c643306ecabb14c31
clash next 5119910629a6bc760199c643306ecabb14c31
clash generate-stub rust
```

**Expected behavior**
At the very least the stub generator should not crash unexpectedly. I don't think it's necessary to make `gameloop` actually work; we could either simply exit with an error, or ignore it (and print a warning) and print the part of the stub that our stub generator can handle. Either way the `Parser::parse` method should probably return a `Result` instead of panicking.

### PR DESCRIPTION
**Pull request by daxida**
image

Fixes #50

### CODE REVIEW

File: src/stub/parser.rs [hunk 1]
```diff
@@ -40,6 +42,7 @@ impl<'a> Parser<'a> {
                 "OUTPUT"    => self.parse_output_comment(&mut stub.commands),
                 "INPUT"     => self.parse_input_comment(&mut stub.commands),
                 "STATEMENT" => stub.statement = self.parse_text_block(),
+                "gameloop"  => return Err(anyhow!("Gameloop keyword is not supported.")),
```
Comment (Andriamanitra) [inline src/stub/parser.rs]: CodinGame refers to them as commands so we should too. I'm not sure how to word it well but we should make it clear to a user that they did nothing wrong but there is no bug to report either - ideally even if the user doesn't know anything about CodinGame's stub system.
```suggestion
                "gameloop"  => return Err(anyhow!("Stub generator does not currently support the 'gameloop' command")),
```

**Review by Andriamanitra — APPROVED** [review]

**Review by ellnix — APPROVED** [review]
It looks good, although it should probably be squashed into one commit.
